Repository hotosm/fAIr, pull requests merged in 2023-08, with the labels that each got.

#135 Updated Readme.md
  Readme.md
  docs/assets/fAIr1.jpg
  docs/assets/fAIr2.jpg
  docs/assets/fair 3.png
Labels: documentation, Outreachy

#146 Backend doc
  backend/docs/.$fAIr_backend.drawio.bkp
  backend/docs/backend_README.md
  backend/docs/fAIr_backend.drawio
  backend/docs/fAIr_backend.png
Labels: Needs Review

#144 Create User-Manual-for-fAIr.md
  docs/User-Manual-for-fAIr.md
Labels: documentation, Needs Review, priority:high, Outreachy
